### ISSUE TITLE
SQL script not parsed entirely

### ISSUE THREAD

**Issue by Zawuza** [viant/dsunit#14]
Hello!

There is one more issue I experienced while using dsunit. In my init file I have a reference to a following SQL script:

```
CREATE TABLE languages(
  code CHAR(2) NOT NULL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE words(
  id NUMERIC NOT NULL PRIMARY KEY,
  language CHAR(2) NOT NULL REFERENCES languages,
  name TEXT UNIQUE NOT NULL
);

CREATE FUNCTION insert_language_trigger() 
  RETURNS TRIGGER
  LANGUAGE plpgsql AS
  $$
  BEGIN
    NEW.code := '11';
    RETURN NEW;
  END
  $$;

CREATE TRIGGER insert_language BEFORE INSERT 
  ON languages
  FOR EACH ROW
  EXECUTE PROCEDURE insert_language_trigger();

INSERT INTO languages(name) VALUES ('Russian');
```
I expect that this script will be executed completely, but after looking into logs, I saw that nothing after "CREATE TABLE words (...);" was executed. No trigger was created and the language was not inserted. 

I debugged the problem and found out that the function ParseSQLScript in parser.go doesn't recognize CREATE FUNCTION as a proper command and can't parse it. 

This script is taken from https://github.com/Zawuza/dsunit-not-working
If one executed the test from this repo and checked the database, then the following could be observed:
1) Two tables "languages" and "words" are present
2) No function or trigger is present, the table "languages" is empty
![image](https://user-images.githubusercontent.com/16268840/60270271-5eb4f000-98f0-11e9-994c-c9b15858582d.png)
![image](https://user-images.githubusercontent.com/16268840/60270689-32e63a00-98f1-11e9-985b-4a5727153255.png)

Regards
Andrei

**Comment by adranwit** [comment]
Addressed in https://github.com/viant/dsunit/releases/tag/v0.9.3

**Comment by Zawuza** [comment]
Thank you very much, both function and trigger are created now!

I found one more small thing that dsunit fails to parse: CREATE OR REPLACE.

I extended the sample in https://github.com/Zawuza/dsunit-not-working with the following:
```
CREATE OR REPLACE FUNCTION insert_language_trigger() 
RETURNS TRIGGER
...
```
This raises an error:
```
failed to execute CREATE OR REPLACE FUNCTION insert_language_trigger() 
  RETURNS TRIGGER
  LANGUAGE plpgsql AS
  $$
  BEGIN
    NEW.code := '11' [] on map[dbname:dsunittestdb] due to:
pq: unterminated dollar-quoted string at or near "$$
  BEGIN
    NEW.code := '11'"
...

**Comment by adranwit** [comment]
Addressed in https://github.com/viant/dsunit/releases/tag/v0.9.4

Tnx

**Comment by Zawuza** [comment]
Now it works, thank you very much!
